
{u'action': {u'data': {u'board': {u'id': u'55661948744df97e9e36f8a0',
                                  u'name': u'Nick Woodhams - Individual Board',
                                  u'shortLink': u'LDKmlkTt'},
                       u'card': {u'id': u'556d234dd5c11672fc87773e',
                                 u'idShort': 32,
                                 u'name': u'Weekly Commits 06/01-06/05',
                                 u'shortLink': u'Ihfm8e7R'},
                       u'checkItem': {u'id': u'556d234dd5c11672fc877743',
                                      u'name': u'Set up a discovery call with Full Contact',
                                      u'state': u'complete',
                                      u'textData': None},
                       u'checklist': {u'id': u'556d234dd5c11672fc87773f',
                                      u'name': u'Checklist'}},
             u'date': u'2015-06-02T06:41:09.531Z',
             u'id': u'556d50051b616084b4d8c3fa',
             u'idMemberCreator': u'51196fa8e98a8ab4090000c2',
             u'memberCreator': {u'avatarHash': u'2427a755be5ab5d8f5d14411e2ffeb48',
                                u'fullName': u'Nicholas Woodhams',
                                u'id': u'51196fa8e98a8ab4090000c2',
                                u'initials': u'NW',
                                u'username': u'nicholaswoodhams'},
             u'type': u'updateCheckItemStateOnCard'},
 u'model': {u'closed': False,
            u'desc': u'',
            u'descData': None,
            u'id': u'55661948744df97e9e36f8a0',
            u'idOrganization': u'542974ddc64597f4a336125c',
            u'labelNames': {u'black': u'',
                            u'blue': u'',
                            u'green': u'',
                            u'lime': u'',
                            u'orange': u'',
                            u'pink': u'Weekly Commits',
                            u'purple': u'',
                            u'red': u'',
                            u'sky': u'',
                            u'yellow': u''},
            u'name': u'Nick Woodhams - Individual Board',
            u'pinned': False,
            u'prefs': {u'background': u'blue',
                       u'backgroundBrightness': u'unknown',
                       u'backgroundColor': u'#0079BF',
                       u'backgroundImage': None,
                       u'backgroundImageScaled': None,
                       u'backgroundTile': False,
                       u'calendarFeedEnabled': False,
                       u'canBeOrg': True,
                       u'canBePrivate': True,
                       u'canBePublic': True,
                       u'canInvite': True,
                       u'cardAging': u'regular',
                       u'cardCovers': True,
                       u'comments': u'members',
                       u'invitations': u'members',
                       u'permissionLevel': u'org',
                       u'selfJoin': True,
                       u'voting': u'disabled'},
            u'shortUrl': u'https://trello.com/b/LDKmlkTt',
            u'url': u'https://trello.com/b/LDKmlkTt/nick-woodhams-individual-board'}}
