"""empty message

Revision ID: 492155420b67
Revises: 1baa18fef687
Create Date: 2015-06-02 03:05:24.080496

"""

# revision identifiers, used by Alembic.
revision = '492155420b67'
down_revision = '1baa18fef687'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trello_card_id', sa.String(length=255), nullable=True),
    sa.Column('slack_message_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    ### end Alembic commands ###
